services:
  django:
    build:
      context: .
      dockerfile: ./software_engineering/Dockerfile
    container_name: django
    env_file:
      - .env
    command: python software_engineering/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: ./software_engineering/Dockerfile
    container_name: test
    command: python software_engineering/manage.py test myapp.tests
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
    depends_on:
      - pgdb

volumes:
  pgdata:
