services:
  django:
    build:
      context: .
      dockerfile: ./software_engineering/Dockerfile
    container_name: django
    volumes:
      - .:/usr/src/app
    ports:
      - "9999:9999"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
volumes:
  pgdata:
