name: software-engineering-lab-9

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Set up Docker Compose
        run: docker-compose up -d
      - name: Generate API documentation
        run: docker-compose exec django python software_engineering/manage.py generateschema > docs.json
      - name: Commit and push documentation
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json index.html # modify the paths if necessary
          git commit -m "Updated documentation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Tear down Docker Compose
        run: docker-compose down
